Text
bossmonkey98/Component_lib pull request #2
Opened 2022-02-08 20:35 UTC by bossmonkey98

PR review for Buttons

2022-02-08 21:23 UTC, bhushannaikaroskar requested changes
There are multiple places you have used rems instead of px and vice versa. I would say to use pixels wherever its is  less thatn 10px and values in rem wherever it is more than 10px

2022-02-08 21:23 UTC, bhushannaikaroskar commented on assets/pages/buttons.css
> +.secondary-btn{
give spacing here for better readability and better structure

2022-02-08 21:23 UTC, bhushannaikaroskar commented on assets/pages/buttons.css
> +.icon-with-text{
same goes here I would suggest use spacing wherever required

2022-02-08 21:23 UTC, bhushannaikaroskar commented on assets/pages/buttons.css
> +}
use font size in px wherever the size is less that 10px.

2022-02-08 21:23 UTC, bhushannaikaroskar commented on assets/pages/buttons.css
> +}
Use pixels here

2022-02-08 21:23 UTC, bhushannaikaroskar commented on assets/pages/buttons.css
> +}
use rem here in height

2022-02-08 21:35 UTC, bhushannaikaroskar approved these changes
As of now I am approving but please do the needful before moving ahead.

2022-02-09 01:09 UTC, zoef-yt requested changes
Do make changes suggested by Bhushan

2022-02-09 01:09 UTC, zoef-yt commented on assets/pages/buttons.css
> +
Remove extra spacing.

2022-02-09 01:09 UTC, zoef-yt commented on assets/pages/buttons.css
> +    background-color: white;
Use var

2022-02-09 03:28 UTC, developer-anand approved these changes
Go to go with changes.

2022-02-09 03:28 UTC, developer-anand commented on assets/pages/buttons.css
> +.link-btn{
use px for less than 10

2022-02-09 06:13 UTC, merged